apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: secure
  labels:
    app: mysql
    tier: backend
spec:
  ports:
     - port: 3306
  selector:
    app: mysql
    tier: backend
  clusterIP: None
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: secure
  labels:
    app: mysql
    tier: backend
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-container
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: rpass
        - name: MYSQL_DATABASE
          value: mydb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef: 
              name: mysql-secret 
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef: 
               name: mysql-secret 
               key: upass
        ports:
        - containerPort: 3306
          name: mysqls
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql